server:
  host: !env [ONCALL_LISTEN_ADDRESS, 0.0.0.0]
  port: !env [ONCALL_LISTEN_PORT, 8080]
debug: !env [ONCALL_DEBUG, False]
oncall_host: !env [ONCALL_HOST, http://localhost:8080]
metrics: dummy
db:
  conn:
    kwargs:
      scheme: mysql+pymysql
      user: !env [ONCALL_DB_USER, oncall]
      password: !env [ONCALL_DB_PASSWORD]
      host: !env [ONCALL_DB_HOST]
      port: !env [ONCALL_DB_PORT, 3306]
      database: !env [ONCALL_DB_DATABASE, oncall]
      charset: utf8
      echo: True
    str: "%(scheme)s://%(user)s:%(password)s@%(host)s/%(database)s?charset=%(charset)s"
  kwargs:
    pool_recycle: 3600
session:
  encrypt_key: 'abc'
  sign_key: '123'
auth:
  debug: False
  module: 'oncall.auth.modules.debug'
notifier:
  skipsend: True
healthcheck_path: /tmp/status
messengers:
  - type: dummy
    application: oncall
    iris_api_key: magic

# allow_origins_list:
#   - http://www.example.com

supported_timezones:
  - &default_tz !env [TZ, 'Europe/Prague']

index_content_setting:
  #footer: |
  #  <ul>
  #    <li>Oncall Â© LinkedIn 2020</li>
  #    <li>Feedback</li>
  #    <li><a href="http://oncall.tools" target="_blank">About</a></li>
  #  </ul>
  missing_number_note: 'No number'

notifications:
  default_roles:
    - "primary"
    - "secondary"
    - "shadow"
    - "manager"
  default_times:
    - 86400
    - 604800
  default_modes:
    - "email"

reminder:
  activated: True
  polling_interval: 360
  default_timezone: !env [TZ, *default_tz]

user_validator:
  activated: True
  subject: 'Warning: Missing phone number in Oncall'
  body: 'You are scheduled for an on-call shift in the future, but have no phone number recorded. Please update your information in Oncall.'

slack_instance: foobar
header_color: '#3a3a3a'
team_managed_message: 'Managed team - this team is managed via API'
